"""adding price to fruits

Revision ID: 5298dfcf76e9
Revises: 953cb169c6f9
Create Date: 2017-11-28 14:36:36.722541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5298dfcf76e9'
down_revision = '953cb169c6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fruits', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('fruits', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fruits', 'price')
    op.drop_column('fruits', 'image')
    # ### end Alembic commands ###
