"""adding image to fruits

Revision ID: 953cb169c6f9
Revises: 38b5e47a3ee2
Create Date: 2017-11-28 14:07:52.554218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953cb169c6f9'
down_revision = '38b5e47a3ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fruits', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fruits', 'image')
    # ### end Alembic commands ###
